name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Orders One Cold Brew
      id: orders-one-cold-brew
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Orders One Cold Brew
        setup-command: ''
        command: javac src/Main.java && java -cp src Main
        input: |-
          1
          0
        expected-output: 'Order complete! Your total is: $4.5'
        comparison-method: contains
        timeout: 2
        max-score: 33
    - name: Orders Both Drinks
      id: orders-both-drinks
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Orders Both Drinks
        setup-command: ''
        command: javac src/Main.java && java -cp src Main
        input: |-
          1
          2
          1
          0
        expected-output: 'Order complete! Your total is: $14.0'
        comparison-method: contains
        timeout: 2
        max-score: 33
    - name: The Window Shopper
      id: the-window-shopper
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: The Window Shopper
        setup-command: ''
        command: javac src/Main.java && java -cp src Main
        input: '0'
        expected-output: 'Order complete! Your total is: $0.0'
        comparison-method: contains
        timeout: 2
        max-score: 34
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ORDERS-ONE-COLD-BREW_RESULTS: "${{steps.orders-one-cold-brew.outputs.result}}"
        ORDERS-BOTH-DRINKS_RESULTS: "${{steps.orders-both-drinks.outputs.result}}"
        THE-WINDOW-SHOPPER_RESULTS: "${{steps.the-window-shopper.outputs.result}}"
      with:
        runners: orders-one-cold-brew,orders-both-drinks,the-window-shopper
